# Generated by Django 5.2.6 on 2025-11-16 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='posts.post'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'created_at'], name='posts_author__d19a82_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='posts_created_060265_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['privacy_level'], name='posts_privacy_45ed47_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content_type'], name='posts_content_7dc73e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['likes_count'], name='posts_likes_c_1d1075_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['post', 'order'], name='post_media_post_id_fc20f0_idx'),
        ),
    ]
